# Lab 1 Tensors and Operations: Deliverables

## Exercise 1: Tensor Creation, Inspection, and Initialization

### Task01:
- Objective: Create a scalar (rank 0), a vector (rank 1 with 5 elements), and a matrix (rank 2 of size 2×3) using tf.constant(), and print their shape and data type.

- Key Concept: Rank and Shape

In [ ]:
import tensorflow as tf

# Scalar (Rank 0)
scalar = tf.constant(5)
print("Scalar:")
print("Value:", scalar)
print("Shape:", scalar.shape)
print("Dtype:", scalar.dtype)
print()

# Vector (Rank 1 with 5 elements)
vector = tf.constant([1, 2, 3, 4, 5])
print("Vector:")
print("Value:", vector)
print("Shape:", vector.shape)
print("Dtype:", vector.dtype)
print()

# Matrix (Rank 2 with shape 2x3)
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6]])
print("Matrix:")
print("Value:", matrix)
print("Shape:", matrix.shape)
print("Dtype:", matrix.dtype)


Scalar:
Value: tf.Tensor(5, shape=(), dtype=int32)
Shape: ()
Dtype: <dtype: 'int32'>

Vector:
Value: tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
Shape: (5,)
Dtype: <dtype: 'int32'>

Matrix:
Value: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape: (2, 3)
Dtype: <dtype: 'int32'>


### Task02:
- Objective: Create a tensor, A, of shape (4, 4) filled with random numbers from a uniform distribution between 10 and 20. Then, create a new tensor, B, filled with zeros but having the same shape and data type as A using tf.zeros_like().

- Key Concept: Initialization functions.

In [1]:
import tensorflow as tf

# Create tensor A with random values between 10 and 20
A = tf.random.uniform(shape=(4, 4), minval=10, maxval=20, dtype=tf.float32)

# Create tensor B with zeros, same shape and dtype as A
B = tf.zeros_like(A)

print("Tensor A:")
print(A)
print("Shape:", A.shape)
print("Dtype:", A.dtype)
print()

print("Tensor B:")
print(B)
print("Shape:", B.shape)
print("Dtype:", B.dtype)


Tensor A:
tf.Tensor(
[[16.670784  12.742444  13.823772  12.43116  ]
 [10.396337  13.064831  14.473892  13.686414 ]
 [13.962105  15.9006605 16.718252  17.684486 ]
 [14.435795  14.209895  17.881765  10.425471 ]], shape=(4, 4), dtype=float32)
Shape: (4, 4)
Dtype: <dtype: 'float32'>

Tensor B:
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(4, 4), dtype=float32)
Shape: (4, 4)
Dtype: <dtype: 'float32'>


Task03:
- Objective: Generate a 3x3 matrix, W, filled with values from a normal (Gaussian) distribution having a mean of 5.0 and a standard deviation (stddev) of 1.0.
- Key Concept: Statistical initialization.

In [2]:
import tensorflow as tf

# Generate 3x3 matrix with normal distribution (mean=5.0, stddev=1.0)
W = tf.random.normal(shape=(3, 3), mean=5.0, stddev=1.0, dtype=tf.float32)

print("Matrix W:")
print(W)
print("Shape:", W.shape)
print("Dtype:", W.dtype)


Matrix W:
tf.Tensor(
[[6.265788  5.740285  3.874259 ]
 [5.0905924 4.27785   5.491261 ]
 [4.3074    4.938194  4.033128 ]], shape=(3, 3), dtype=float32)
Shape: (3, 3)
Dtype: <dtype: 'float32'>


## Exercise 2: Variables and Mutability

Task01
- Objective: Define a variable V_weights initialized as a 2x2 matrix using tf.Variable(). Confirm its initialization value using .numpy().
- Key Concept: tf.Variable definition.

In [3]:
import tensorflow as tf

# Define a 2x2 variable matrix
V_weights = tf.Variable([[1.0, 2.0],
                         [3.0, 4.0]])

# Confirm initialization value
print("V_weights:")
print(V_weights.numpy())
print("Shape:", V_weights.shape)
print("Dtype:", V_weights.dtype)


V_weights:
[[1. 2.]
 [3. 4.]]
Shape: (2, 2)
Dtype: <dtype: 'float32'>


Task02
- Objective: Use the .assign() method to change the value of the bottom-right element of V_weights to 99.0. Print V_weights to confirm the update.
- Key Concept: Mutability and .assign().

In [4]:
import tensorflow as tf

# Initialize the variable (from Task 01)
V_weights = tf.Variable([[1.0, 2.0],
                         [3.0, 4.0]])

# Update the bottom-right element to 99.0
V_weights.assign([[1.0, 2.0],
                  [3.0, 99.0]])

# Confirm the update
print("Updated V_weights:")
print(V_weights.numpy())


Updated V_weights:
[[ 1.  2.]
 [ 3. 99.]]


Task03
- Define a constant, C_const, and attempt to update one of its elements directly (e.g., using .assign()). Observe and explain the resulting error.
- Immutability of tf.constant and tf.Tensor.


In [5]:
import tensorflow as tf

# Define a constant tensor
C_const = tf.constant([[1, 2],
                       [3, 4]])

print("C_const:")
print(C_const)

# Attempt to modify the constant tensor
try:
    C_const.assign([[1, 2],
                    [3, 99]])
except Exception as e:
    print("\nError while updating C_const:")
    print(e)


C_const:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

Error while updating C_const:
'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'


# Exercise 3: Reshaping and Indexing Data

Task01:
- Objective: Create a tensor T using tf.range(16). Reshape T into a 4x4 matrix, T_matrix. Then, reshape T_matrix back into a 1D vector, T_vector, allowing TensorFlow to infer the size of the single dimension by using -1.
- Key Concept: tf.reshape() and inferred size (-1).

In [6]:
import tensorflow as tf

# Create a 1D tensor with values from 0 to 15
T = tf.range(16)

# Reshape into a 4x4 matrix
T_matrix = tf.reshape(T, (4, 4))

# Reshape back into a 1D vector using inferred size (-1)
T_vector = tf.reshape(T_matrix, (-1,))

print("Original Tensor T:")
print(T)
print("Shape:", T.shape)
print()

print("Reshaped Tensor T_matrix (4x4):")
print(T_matrix)
print("Shape:", T_matrix.shape)
print()

print("Reshaped Tensor T_vector (1D):")
print(T_vector)
print("Shape:", T_vector.shape)


Original Tensor T:
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15], shape=(16,), dtype=int32)
Shape: (16,)

Reshaped Tensor T_matrix (4x4):
tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]], shape=(4, 4), dtype=int32)
Shape: (4, 4)

Reshaped Tensor T_vector (1D):
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15], shape=(16,), dtype=int32)
Shape: (16,)


Task02:
- Objective: Create a 3x4x2 tensor D (rank 3) filled with random integers (maxval=50). Access and print the entire second slice along the first dimension (axis=0). Then, access the element at index ``.
- Key Concept: Indexing and Slicing (e.g., x[a, b, c]).

In [7]:
import tensorflow as tf

# Create a 3x4x2 tensor with random integers
D = tf.random.uniform(shape=(3, 4, 2),
                      minval=0,
                      maxval=50,
                      dtype=tf.int32)

print("Tensor D:")
print(D)
print("Shape:", D.shape)
print()

# Access the second slice along the first dimension (axis = 0)
second_slice = D[1]
print("Second slice along axis 0 (D[1]):")
print(second_slice)
print()

# Access a specific element (example: index [1, 2, 0])
element = D[1, 2, 0]
print("Element at index D[1, 2, 0]:")
print(element)


Tensor D:
tf.Tensor(
[[[46 39]
  [13 12]
  [34 32]
  [13 19]]

 [[11 12]
  [34 23]
  [47 15]
  [41 42]]

 [[46 22]
  [43 16]
  [ 3 46]
  [ 4 21]]], shape=(3, 4, 2), dtype=int32)
Shape: (3, 4, 2)

Second slice along axis 0 (D[1]):
tf.Tensor(
[[11 12]
 [34 23]
 [47 15]
 [41 42]], shape=(4, 2), dtype=int32)

Element at index D[1, 2, 0]:
tf.Tensor(47, shape=(), dtype=int32)


Task03:
- Objective: Using T (tf.range(16)), slice and print every third element starting from the second element (index 1).
- Key Concept: Slicing with start:end:step.

In [8]:
import tensorflow as tf

# Create tensor T
T = tf.range(16)

# Slice every third element starting from index 1
sliced_T = T[1::3]

print("Original Tensor T:")
print(T)
print()

print("Sliced Tensor (every 3rd element starting from index 1):")
print(sliced_T)


Original Tensor T:
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15], shape=(16,), dtype=int32)

Sliced Tensor (every 3rd element starting from index 1):
tf.Tensor([ 1  4  7 10 13], shape=(5,), dtype=int32)


# Exercise 4: Matrix Operations and Broadcasting


Task01
- Objective: Define a 3x2 matrix M1 and a 2x4 matrix M2. Calculate the matrix product P = M1 @ M2 using the @ operator or tf.matmul(). Print the shape of the result P (it should be 3x4).
- Key Concept: Matrix Algebra (@).

In [10]:
import tensorflow as tf

# Define matrices
M1 = tf.constant([[1, 2],
                  [3, 4],
                  [5, 6]])   # Shape: (3, 2)

M2 = tf.constant([[1, 2, 3, 4],
                  [5, 6, 7, 8]])  # Shape: (2, 4)

# Matrix multiplication using @ operator
P = M1 @ M2
# Alternatively: P = tf.matmul(M1, M2)

print("Matrix M1:")
print(M1)
print("Shape:", M1.shape)
print()

print("Matrix M2:")
print(M2)
print("Shape:", M2.shape)
print()

print("Product Matrix P (M1 @ M2):")
print(P)
print("Shape:", P.shape)


Matrix M1:
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Shape: (3, 2)

Matrix M2:
tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)
Shape: (2, 4)

Product Matrix P (M1 @ M2):
tf.Tensor(
[[11 14 17 20]
 [23 30 37 44]
 [35 46 57 68]], shape=(3, 4), dtype=int32)
Shape: (3, 4)


Task02
- Objective: Define a vector V_scale = [2., 2., 2.]. Calculate B_out = M1 * V_scale using element-wise multiplication. Explain why this operation works even though M1 is 3x2 and V_scale is rank 1.
- Key Concept: Implicit Broadcasting.

In [11]:
import tensorflow as tf

# Define matrix M1 (3x2)
M1 = tf.constant([[1., 2.],
                  [3., 4.],
                  [5., 6.]])

# Define scaling vector
V_scale = tf.constant([2., 2., 2.])

# Element-wise multiplication using broadcasting
B_out = M1 * tf.reshape(V_scale, (3, 1))

print("Matrix M1:")
print(M1)
print("Shape:", M1.shape)
print()

print("Scaling Vector V_scale:")
print(V_scale)
print("Shape:", V_scale.shape)
print()

print("Output after Broadcasting (B_out):")
print(B_out)
print("Shape:", B_out.shape)


Matrix M1:
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32)
Shape: (3, 2)

Scaling Vector V_scale:
tf.Tensor([2. 2. 2.], shape=(3,), dtype=float32)
Shape: (3,)

Output after Broadcasting (B_out):
tf.Tensor(
[[ 2.  4.]
 [ 6.  8.]
 [10. 12.]], shape=(3, 2), dtype=float32)
Shape: (3, 2)


Task03:
- Objective: Define a scalar S = 5.0. Manually use tf.broadcast_to() to expand S into a 3x2 matrix, S_matrix. Verify that M1 + S produces the exact same result as M1 + S_matrix.
- Key Concept: Explicit Broadcasting (tf.broadcast_to).

In [12]:
import tensorflow as tf

# Define matrix M1 (3x2)
M1 = tf.constant([[1., 2.],
                  [3., 4.],
                  [5., 6.]])

# Define scalar
S = tf.constant(5.0)

# Explicitly broadcast scalar to 3x2 matrix
S_matrix = tf.broadcast_to(S, shape=(3, 2))

# Add scalar and broadcasted matrix to M1
result_scalar_add = M1 + S
result_matrix_add = M1 + S_matrix

print("Matrix M1:")
print(M1)
print()

print("Broadcasted Scalar Matrix S_matrix:")
print(S_matrix)
print()

print("Result of M1 + S:")
print(result_scalar_add)
print()

print("Result of M1 + S_matrix:")
print(result_matrix_add)
print()

# Verify both results are identical
print("Are both results equal?",
      tf.reduce_all(result_scalar_add == result_matrix_add).numpy())


Matrix M1:
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32)

Broadcasted Scalar Matrix S_matrix:
tf.Tensor(
[[5. 5.]
 [5. 5.]
 [5. 5.]], shape=(3, 2), dtype=float32)

Result of M1 + S:
tf.Tensor(
[[ 6.  7.]
 [ 8.  9.]
 [10. 11.]], shape=(3, 2), dtype=float32)

Result of M1 + S_matrix:
tf.Tensor(
[[ 6.  7.]
 [ 8.  9.]
 [10. 11.]], shape=(3, 2), dtype=float32)

Are both results equal? True


# Exercise 5: Data Types and Casting

Task01:
- Objective: Define a tensor F_float containing floating-point values: [1.9, 2.1, 3.5, 4.0] (dtype=float32). Use tf.cast() to convert F_float to integer type (tf.int32). Note and explain the conversion outcome (truncation, not rounding).
- Key Concept: Type Casting and Truncation.

In [13]:
import tensorflow as tf

# Define float tensor
F_float = tf.constant([1.9, 2.1, 3.5, 4.0], dtype=tf.float32)

# Cast to int32
F_int = tf.cast(F_float, dtype=tf.int32)

print("Original Float Tensor (F_float):")
print(F_float)
print("Dtype:", F_float.dtype)
print()

print("Casted Integer Tensor (F_int):")
print(F_int)
print("Dtype:", F_int.dtype)


Original Float Tensor (F_float):
tf.Tensor([1.9 2.1 3.5 4. ], shape=(4,), dtype=float32)
Dtype: <dtype: 'float32'>

Casted Integer Tensor (F_int):
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Dtype: <dtype: 'int32'>


Task02:
- Objecctive: Define a tensor B_bool containing booleans: [True, False, True, True]. Cast B_bool to tf.int32. Also, define an integer tensor I_int = [-5, 0, 1] and cast it to tf.bool. Explain the resulting integer/boolean representations.
- Key Concept: Boolean-Integer Mapping.

In [14]:
import tensorflow as tf

# Define boolean tensor
B_bool = tf.constant([True, False, True, True])

# Cast boolean tensor to int32
B_int = tf.cast(B_bool, dtype=tf.int32)

print("Boolean Tensor (B_bool):")
print(B_bool)
print("Dtype:", B_bool.dtype)
print()

print("Casted Integer Tensor (B_int):")
print(B_int)
print("Dtype:", B_int.dtype)
print()

# Define integer tensor
I_int = tf.constant([-5, 0, 1])

# Cast integer tensor to bool
I_bool = tf.cast(I_int, dtype=tf.bool)

print("Integer Tensor (I_int):")
print(I_int)
print("Dtype:", I_int.dtype)
print()

print("Casted Boolean Tensor (I_bool):")
print(I_bool)
print("Dtype:", I_bool.dtype)


Boolean Tensor (B_bool):
tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)
Dtype: <dtype: 'bool'>

Casted Integer Tensor (B_int):
tf.Tensor([1 0 1 1], shape=(4,), dtype=int32)
Dtype: <dtype: 'int32'>

Integer Tensor (I_int):
tf.Tensor([-5  0  1], shape=(3,), dtype=int32)
Dtype: <dtype: 'int32'>

Casted Boolean Tensor (I_bool):
tf.Tensor([ True False  True], shape=(3,), dtype=bool)
Dtype: <dtype: 'bool'>


Task03:
- Objective: Define an integer constant equal to 123456789 with tf.int32 precision. Attempt to cast this constant to tf.int16. Observe and explain the output, noting that insufficient bit length can lead to data overflow and incorrect results.
- Key Concept: Numerical Precision and Overflow Risk.

In [15]:
import tensorflow as tf

# Define int32 constant
large_int = tf.constant(123456789, dtype=tf.int32)

# Cast to int16
casted_int16 = tf.cast(large_int, dtype=tf.int16)

print("Original int32 value:")
print(large_int.numpy())
print("Dtype:", large_int.dtype)
print()

print("Casted int16 value:")
print(casted_int16.numpy())
print("Dtype:", casted_int16.dtype)


Original int32 value:
123456789
Dtype: <dtype: 'int32'>

Casted int16 value:
-13035
Dtype: <dtype: 'int16'>
