In [1]:
# PART A: Manual Word-Level One-Hot Encoding (Implementation + vocabulary construction)
import numpy as np
chars = ['a','b','c','d']
char_index = {c:i for i,c in enumerate(chars)}
def char_one_hot(ch):
    vec = np.zeros(len(chars))
    vec[char_index[ch]] = 1
    return vec
print(char_one_hot('b'))

[0. 1. 0. 0.]


In [2]:
import numpy as np
words = ["cat", "dog", "fish"]
vocab = {w:i for i,w in enumerate(words)}
vocab_size = len(vocab)
print("Vocabulary:", vocab)
def one_hot(word):
    vec = np.zeros(vocab_size)
    vec[vocab[word]] = 1
    return vec
print("cat:", one_hot("cat"))
print("dog:", one_hot("dog"))


Vocabulary: {'cat': 0, 'dog': 1, 'fish': 2}
cat: [1. 0. 0.]
dog: [0. 1. 0.]


In [3]:
# PART B: Manual Character-Level One-Hot Encoding (Character vocabulary)
import numpy as np
char = ['a', 'b', 'c', 'd']
for i, ch in enumerate(char):
    print(i, ch)

vocab = {ch:i for i,ch in enumerate(char)}
vocab_size = len(vocab)
print(vocab)
def one_hot(word):
    vec = np.zeros(vocab_size)
    vec[vocab[word]] = 1
    return vec
print("c:", one_hot("c"))
print("d:", one_hot("d"))


0 a
1 b
2 c
3 d
{'a': 0, 'b': 1, 'c': 2, 'd': 3}
c: [0. 0. 1. 0.]
d: [0. 0. 0. 1.]


In [4]:
# PART C: Keras one_hot() — The Hashing Trick (Fixed-size encoding with collision analysis)
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
text1 = "cat dog fish dog"
text2 = "lion elephant"
encoded = []
encoded.append(one_hot(text1, 10))
encoded.append(one_hot(text2, 10))
print(encoded)
padded = pad_sequences(encoded,padding='post')
print(padded)

[[1, 4, 3, 4], [2, 4]]
[[1 4 3 4]
 [2 4 0 0]]


In [5]:
from tensorflow.keras.preprocessing.text import Tokenizer
# Sample corpus
texts = [
"I love AI",
"AI is very powerful"
]
# --------------------------------------------------
# Step 1: Build Vocabulary
# --------------------------------------------------
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)
print("Vocabulary (word → index):")
print(tokenizer.word_index)
# --------------------------------------------------
# Step 2: Convert Text → Integer Sequences
# --------------------------------------------------
sequences = tokenizer.texts_to_sequences(texts)
print("\nInteger Sequences:")
for i, seq in enumerate(sequences):
    print(f"Text {i+1}: {seq}")
# --------------------------------------------------
# Step 3: Convert Text → Matrix Representation
# --------------------------------------------------
matrix = tokenizer.texts_to_matrix(texts, mode='binary')
print("\nMatrix Representation (texts_to_matrix):")
print(matrix)
print("\nMatrix Shape:", matrix.shape)

Vocabulary (word → index):
{'ai': 1, 'i': 2, 'love': 3, 'is': 4, 'very': 5, 'powerful': 6}

Integer Sequences:
Text 1: [2, 3, 1]
Text 2: [1, 4, 5, 6]

Matrix Representation (texts_to_matrix):
[[0. 1. 1. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1. 1. 1.]]

Matrix Shape: (2, 7)
